// <auto-generated />
using EntityFrameWork2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWork2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221120190808_Add City")]
    partial class AddCity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CityVMPersonVM", b =>
                {
                    b.Property<string>("citiesName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("peopleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("citiesName", "peopleId");

                    b.HasIndex("peopleId");

                    b.ToTable("CityVMPersonVM");
                });

            modelBuilder.Entity("EntityFrameWork1.Models.CityVM", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Name");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            Name = "Åre",
                            PostNumber = "415 55"
                        },
                        new
                        {
                            Name = "Järpen",
                            PostNumber = "415 44"
                        });
                });

            modelBuilder.Entity("EntityFrameWork2.Models.PersonVM", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EfterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "2d3b8d8d-0a91-49e3-9dc7-b27bb73b8a87",
                            EfterName = "khawari",
                            Name = "Ali",
                            PhoneNumber = "1245",
                            age = 32
                        },
                        new
                        {
                            Id = "fae4f872-b5bc-46d6-9e8f-7364bab6babc",
                            EfterName = "khawari22",
                            Name = "Ali22",
                            PhoneNumber = "1245",
                            age = 32
                        },
                        new
                        {
                            Id = "358c9721-60e9-4094-9a6a-793cace7f8a4",
                            EfterName = "khawari33",
                            Name = "Ali33",
                            PhoneNumber = "1245",
                            age = 32
                        });
                });

            modelBuilder.Entity("CityVMPersonVM", b =>
                {
                    b.HasOne("EntityFrameWork1.Models.CityVM", null)
                        .WithMany()
                        .HasForeignKey("citiesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFrameWork2.Models.PersonVM", null)
                        .WithMany()
                        .HasForeignKey("peopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
